# Generated by Django 5.0.4 on 2024-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0003_siteconfig_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='open_ai_model',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
