# Generated by Django 5.0.4 on 2024-04-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatai', '0004_siteconfig_open_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
